In [1]:
import array as arr
import numpy as np

# 1. Creating an Array
my_array = arr.array('i', [1, 2, 3, 4, 5])
print("Original Array (using array module):")
print(my_array)

# 2. Accessing Elements
print("\nAccessing Elements:")
print("First element:", my_array[0])
print("Last element:", my_array[-1])

# 3. Appending Items
my_array.append(6)
print("\nAfter appending 6:")
print(my_array)

# 4. Inserting Items
my_array.insert(2, 99)
print("\nAfter inserting 99 at index 2:")
print(my_array)

# 5. Removing Items
my_array.remove(99)
print("\nAfter removing 99:")
print(my_array)

# 6. Finding Length
length = len(my_array)
print("\nLength of the array:")
print(length)

# 7. Slicing
sliced_array = my_array[1:4]
print("\nSlicing from index 1 to 3:")
print(sliced_array)

# 8. Concatenating Arrays
array1 = arr.array('i', [1, 2, 3])
array2 = arr.array('i', [4, 5, 6])
concatenated_array = array1 + array2
print("\nConcatenation:")
print(concatenated_array)

# 9. Iterating through an Array
print("\nIterating through the array:")
for item in my_array:
    print(item, end=" ")

# 10. Array Functions with numpy
print("\n\nUsing numpy library:")

# Creating a numpy array
np_array = np.array([1, 2, 3, 4, 5])
print("Original Numpy Array:")
print(np_array)

# Array Operations with numpy
print("\nNumpy Array Operations:")

# Adding a constant
np_array = np_array + 1
print("After adding 1 to each element:", np_array)

# Element-wise addition
np_array2 = np.array([5, 4, 3, 2, 1])
result_array = np_array + np_array2
print("Element-wise addition with [5, 4, 3, 2, 1]:", result_array)

# Multiplying by a constant
np_array = np_array * 2
print("After multiplying each element by 2:", np_array)

# Element-wise multiplication
result_array = np_array * np_array2
print("Element-wise multiplication with [5, 4, 3, 2, 1]:", result_array)

# Slicing
print("Slicing numpy array from index 1 to 3:", np_array[1:4])

# Finding the mean
mean_value = np.mean(np_array)
print("Mean of the numpy array:", mean_value)

# Finding the maximum and minimum
max_value = np.max(np_array)
min_value = np.min(np_array)
print("Max value:", max_value)
print("Min value:", min_value)

# Transposing a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])
transposed_matrix = np.transpose(matrix)
print("Original matrix:")
print(matrix)
print("Transposed matrix:")
print(transposed_matrix)


Original Array (using array module):
array('i', [1, 2, 3, 4, 5])

Accessing Elements:
First element: 1
Last element: 5

After appending 6:
array('i', [1, 2, 3, 4, 5, 6])

After inserting 99 at index 2:
array('i', [1, 2, 99, 3, 4, 5, 6])

After removing 99:
array('i', [1, 2, 3, 4, 5, 6])

Length of the array:
6

Slicing from index 1 to 3:
array('i', [2, 3, 4])

Concatenation:
array('i', [1, 2, 3, 4, 5, 6])

Iterating through the array:
1 2 3 4 5 6 

Using numpy library:
Original Numpy Array:
[1 2 3 4 5]

Numpy Array Operations:
After adding 1 to each element: [2 3 4 5 6]
Element-wise addition with [5, 4, 3, 2, 1]: [7 7 7 7 7]
After multiplying each element by 2: [ 4  6  8 10 12]
Element-wise multiplication with [5, 4, 3, 2, 1]: [20 24 24 20 12]
Slicing numpy array from index 1 to 3: [ 6  8 10]
Mean of the numpy array: 8.0
Max value: 12
Min value: 4
Original matrix:
[[1 2 3]
 [4 5 6]]
Transposed matrix:
[[1 4]
 [2 5]
 [3 6]]
