In [1]:
import numpy as np

def matrix_addition(A, B):
    if A.shape != B.shape:
        raise ValueError("Matrices must have the same dimensions for addition.")
    return A + B

def matrix_subtraction(A, B):
    if A.shape != B.shape:
        raise ValueError("Matrices must have the same dimensions for subtraction.")
    return A - B

def matrix_multiplication(A, B):
    if A.shape[1] != B.shape[0]:
        raise ValueError("Number of columns in the first matrix must be equal to the number of rows in the second matrix.")
    return np.dot(A, B)

def matrix_transpose(A):
    return A.T

def matrix_determinant(A):
    if A.shape[0] != A.shape[1]:
        raise ValueError("Matrix must be square to calculate the determinant.")
    return np.linalg.det(A)

# Example usage
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

# Matrix Addition
C = matrix_addition(A, B)
print("\nMatrix Addition (A + B):")
print(C)

# Matrix Subtraction
D = matrix_subtraction(A, B)
print("\nMatrix Subtraction (A - B):")
print(D)

# Matrix Multiplication
E = matrix_multiplication(A, B)
print("\nMatrix Multiplication (A * B):")
print(E)

# Matrix Transpose
F = matrix_transpose(A)
print("\nMatrix Transpose (A^T):")
print(F)

# Matrix Determinant
det_A = matrix_determinant(A)
print("\nMatrix Determinant (det(A)):")
print(det_A)


Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Matrix Addition (A + B):
[[ 6  8]
 [10 12]]

Matrix Subtraction (A - B):
[[-4 -4]
 [-4 -4]]

Matrix Multiplication (A * B):
[[19 22]
 [43 50]]

Matrix Transpose (A^T):
[[1 3]
 [2 4]]

Matrix Determinant (det(A)):
-2.0000000000000004
